### ISSUE TITLE
Translation: Compute: A brief history

### ISSUE THREAD

**Issue by yangchuansheng** [kubesphere-sigs/awesome-cloud-native-blogs#1]
### 本文的类型为？

翻译

### 原文链接

https://medium.com/@wajdi.fathallah/compute-a-brief-history-f65f4e7e5caf

### 原文发布时间

2021-08-03

### 作者

Wajdi Fathallah

### 标签

kind/translation

### 已提交文章线索？

yes

### 已有人认领翻译或为原创文章？

yes

### 已提交 PR？

no

### 正在review？

no

### review 完成等待发布？

no

### 已发布到 http://kubesphere.com.cn？

no

### 已发布到 「KubeSphere 云原生」 微信公众号？

no

**Comment by klaylin** [comment]
认领
