### ISSUE TITLE
Translation: Making JavaScript run fast on WebAssembly

### ISSUE THREAD

**Issue by yangchuansheng** [kubesphere-sigs/awesome-cloud-native-blogs#19]
### 本文的类型为？

翻译

### 原文链接

https://bytecodealliance.org/articles/making-javascript-run-fast-on-webassembly

### 原文发布时间

2021-06-02

### 作者

Lin Clark

### 标签

kind/translation

### 已提交文章线索？

yes

### 已有人认领翻译或为原创文章？

no

### 已提交 PR？

no

### 正在review？

no

### review 完成等待发布？

no

### 已发布到 http://kubesphere.com.cn？

no

### 已发布到 「KubeSphere 云原生」 微信公众号？

no

**Comment by 1020973418** [comment]
领认
