### ISSUE TITLE
Translation: Getting Started with eBPF and Go

### ISSUE THREAD

**Issue by yangchuansheng** [kubesphere-sigs/awesome-cloud-native-blogs#2]
### 本文的类型为？

翻译

### 原文链接

https://networkop.co.uk/post/2021-03-ebpf-intro/

### 原文发布时间

2021-05-08

### 作者

Michael Kashin

### 标签

kind/translation

### 已提交文章线索？

yes

### 已有人认领翻译或为原创文章？

yes

### 已提交 PR？

no

### 正在review？

no

### review 完成等待发布？

no

### 已发布到 http://kubesphere.com.cn？

no

### 已发布到 「KubeSphere 云原生」 微信公众号？

no

**Comment by bigdimple** [comment]
已有人认领翻译或为原创文章？
yes

**Comment by yangchuansheng** [comment]
> 已有人认领翻译或为原创文章？
> yes

这篇文章进度如何？
