### ISSUE TITLE
An eBPF overview, part 2: Machine & bytecode

### ISSUE THREAD

**Issue by yangchuansheng** [kubesphere-sigs/awesome-cloud-native-blogs#27]
### 本文的类型为？

翻译

### 原文链接

https://www.collabora.com/news-and-blog/blog/2019/04/15/an-ebpf-overview-part-2-machine-and-bytecode/

### 原文发布时间

2019-04-15

### 作者

Adrian Ratiu

### 标签

kind/translation

### 已提交文章线索？

yes

### 已有人认领翻译或为原创文章？

no

### 已提交 PR？

no

### 正在review？

no

### review 完成等待发布？

no

### 已发布到 http://kubesphere.com.cn？

no

### 已发布到 「KubeSphere 云原生」 微信公众号？

no

**Comment by 1020973418** [comment]
认领
